# Generated by Django 4.2.11 on 2024-05-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_last_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_phone',
        ),
    ]
