# Generated by Django 4.2.11 on 2024-05-12 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_client_city_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
