# Generated by Django 5.0.4 on 2024-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
    ]
