# Generated by Django 5.0.4 on 2024-04-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_client_city_client_telephone_manager_manager_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager_telephone',
            new_name='manager_phone',
        ),
    ]
