# Generated by Django 5.0.4 on 2024-04-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_rename_manager_telephone_manager_manager_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='phone',
        ),
    ]
