# Generated by Django 5.0.4 on 2024-04-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_rename_telephone_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.manager'),
        ),
    ]
