# Generated by Django 5.0.4 on 2024-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_request_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='TourRequest',
        ),
    ]
