# Generated by Django 4.2.11 on 2024-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_rename_request_tourrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=50, null=True)),
                ('place_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
