# Generated by Django 4.2.11 on 2024-05-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address_profile_role_manager_client'),
        ('main_page', '0008_client_user_tourrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
