# Generated by Django 4.2.11 on 2024-05-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address_profile_role_manager_client'),
        ('main_page', '0009_alter_tourrequest_manager_delete_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager'),
        ),
    ]
