# Generated by Django 4.2.11 on 2024-05-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address_profile_role_manager_client'),
        ('main_page', '0010_alter_tourrequest_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourrequest',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
