# Generated by Django 4.2.11 on 2024-05-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address_profile_role_manager_client'),
        ('main_page', '0011_remove_tourrequest_manager_remove_tourrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
