# Generated by Django 4.2.11 on 2024-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_role'),
        ('main_page', '0012_alter_tourrequest_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='tour_requests', to='users.manager'),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='status',
            field=models.CharField(default='В роботі', max_length=50),
        ),
    ]
