# Generated by Django 4.2.11 on 2024-05-12 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_tourrequest_managers_tourrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourrequest',
            old_name='client_name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='child',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='hotel',
            field=models.CharField(default='No hotel', max_length=100),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='nights',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='pax',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tourrequest',
            name='status',
            field=models.CharField(default='не в роботі', max_length=50),
        ),
    ]
