# Generated by Django 4.2.11 on 2024-05-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_client_user_alter_manager_user'),
        ('main_page', '0014_rename_client_name_tourrequest_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
