# Generated by Django 4.2.11 on 2024-05-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_client_user_alter_manager_user'),
        ('main_page', '0015_alter_tourrequest_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
