# Generated by Django 4.2.11 on 2024-05-13 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0016_alter_tourrequest_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourrequest',
            name='client',
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
